import pg8000.native
conn = pg8000.native.Connection(host="aws-1-ap-southeast-1.pooler.supabase.com", port=5432, database="postgres", user="postgres.kzekrzdyyhedstoaihlt", password="\044\046Kilodash123")
rows = conn.run("SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename")
print(f"=== TABLES ({len(rows)}) ===")
for r in rows: print(f"  {r[0]}")
policies = conn.run("SELECT count(*) FROM pg_policies")
print(f"\n=== RLS POLICIES: {policies[0][0]} ===")
indexes = conn.run("SELECT count(*) FROM pg_indexes WHERE schemaname = 'public'")
print(f"=== INDEXES: {indexes[0][0]} ===")
conn.close()
